var avatars = [
  chrome.extension.getURL("../images/avatar1.jpg"),
  chrome.extension.getURL("../images/avatar2.jpg"),
  chrome.extension.getURL("../images/avatar3.jpg"),
  chrome.extension.getURL("../images/avatar4.jpg"),
  chrome.extension.getURL("../images/avatar5.jpg"),
  chrome.extension.getURL("../images/avatar6.jpg"),
  chrome.extension.getURL("../images/avatar7.jpg"),
  chrome.extension.getURL("../images/avatar8.jpg"),
  chrome.extension.getURL("../images/avatar9.jpg"),
  chrome.extension.getURL("../images/avatar10.jpg"),
  chrome.extension.getURL("../images/avatar11.jpg"),
  chrome.extension.getURL("../images/avatar12.jpg"),
  chrome.extension.getURL("../images/avatar13.jpg"),
  chrome.extension.getURL("../images/avatar14.jpg"),
  chrome.extension.getURL("../images/avatar15.jpg"),
  chrome.extension.getURL("../images/avatar16.jpg"),
  chrome.extension.getURL("../images/avatar17.jpg"),
  chrome.extension.getURL("../images/avatar18.jpg"),
  chrome.extension.getURL("../images/avatar19.jpg"),
  chrome.extension.getURL("../images/avatar20.jpg")
]

function changeAvatar(elem, n) {
  if (elem.hasClass("shia")) {
    return;
  } else {
    elem.attr("src", avatars[n]);
    elem.addClass("shia");
  }
}

function changeText(elem, n) {
  if (elem.hasClass("shia")) {
    return;
  } else {
    elem.html(text.gen(n).toUpperCase());
    elem.addClass("shia");
  }
}

/*
function changeAnimated(elem) {
  elem.replaceWith('<img src="')
}
*/

$(document).ready(function(){
  text = new markov(corpus, "string", /[.^\w]+ /g);
  alert("r u ready?");
  // run once after alert
  $('.fullname').each(function () {
      $(this).html("Shia Labeouf");
  });
  $("img").each(function () {
    var n = Math.floor(Math.random() * (avatars.length - 1));
    changeAvatar($(this), n);
  });
  $('.tweet-text').each(function () {
    var m = Math.floor(Math.random() * 28) + 3;
    changeText($(this), m);
  });

  // run on scroll to render elements generated by infinite scroll
  $(window).scroll(function () {
    $('.fullname').each(function () {
      $(this).html("Shia Labeouf");
    });
    $("img").each(function () {
      var n = Math.floor(Math.random() * (avatars.length - 1));
      changeAvatar($(this), n);
    });
    $('.tweet-text').each(function () {
      var m = Math.floor(Math.random() * 28) + 3;
      changeText($(this), m);
    });
  });
})
