var avatars = [
  chrome.extension.getURL("../images/avatar1.jpg"),
  chrome.extension.getURL("../images/avatar2.jpg"),
  chrome.extension.getURL("../images/avatar3.jpg"),
  chrome.extension.getURL("../images/avatar4.jpg"),
  chrome.extension.getURL("../images/avatar5.jpg")
]
function changeAvatar(elem, n) {
  if (elem.hasClass("shia")) {
    return;
  } else {
    elem.attr("src", avatars[n]);
    elem.addClass("shia");
  }
}

function changeText(elem, n) {
  if (elem.hasClass("shia")) {
    return;
  } else {
    elem.html(text.gen(n).toUpperCase());
    elem.addClass("shia");
  }
}

$(document).ready(function(){
  text = new markov(corpus, "string", /[.^\w]+ /g);
  alert("r u ready?");
  // run once after alert
  $('.fullname').each(function () {
      $(this).html("Shia Labeouf");
  });
  $("img").each(function () {
    var n = Math.floor(Math.random() * (avatars.length - 1));
    changeAvatar($(this), n);
  });
  $("video").each(function() {
    $(this).replaceWith(' <img class="shia-gif" /> ');
    $('.shia-gif').each(function(){
      $(this).attr("src", chrome.extension.getURL("../images/clap.gif"));
    });
  });
  $('.tweet-text').each(function () {
    var m = Math.floor(Math.random() * 28) + 3;
    changeText($(this), m);
  });

  // run on scroll to render elements generated by infinite scroll
  $(window).scroll(function () {
    $('.fullname').each(function () {
      $(this).html("Shia Labeouf");
    });
    $("video").each(function() {
      $(this).replaceWith(' <img class="shia-gif shia" /> ');
      $('.shia-gif').each(function(){
        $(this).attr("src", chrome.extension.getURL("../images/clap.gif"));
      });
    });
    $("img").each(function () {
      var n = Math.floor(Math.random() * (avatars.length - 1));
      changeAvatar($(this), n);
    });
    $('.tweet-text').each(function () {
      var m = Math.floor(Math.random() * 28) + 3;
      changeText($(this), m);
    });
  });
})
